name: huellitas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  image_picker: ^1.2.0
  table_calendar: ^3.0.9
  awesome_dialog: ^3.2.0
  dropdown_button2: ^2.3.9
  google_maps_flutter: ^2.6.0


  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
