name: huellitas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  image_picker: ^1.2.0
  table_calendar: ^3.0.9
  awesome_dialog: ^3.2.0
  dropdown_button2: ^2.3.9
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  shared_preferences: ^2.1.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.9.0
  file_picker: ^8.0.5
  js: ^0.6.5
  permission_handler: ^10.4.0


  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
